'use server';

/**
 * @fileOverview An AI shopping assistant that recommends products based on user input.
 *
 * - getProductRecommendations - A function that handles the product recommendation process.
 * - GetProductRecommendationsInput - The input type for the getProductRecommendations function.
 * - GetProductRecommendationsOutput - The return type for the getProductRecommendations function.
 */

import {ai} from '@/ai/genkit';
import type { ProductService, UserProfile } from '@/lib/types';
import {z} from 'genkit';


const ProductSchema = z.object({
  id: z.string().describe('The unique identifier of the product.'),
  name: z.string().describe('The name of the product.'),
  description: z.string().describe('The description of the product.'),
  category: z.string().describe('The category of the product.'),
  price: z.number().describe('The price of the product.'),
});

const GetProductRecommendationsInputSchema = z.object({
  userProfile: z.object({
    summary: z.string(),
    tags: z.array(z.string()),
  }).describe('The user profile generated by another AI.'),
  products: z.array(ProductSchema).describe('The list of available products in the store.'),
  photoDataUri: z
    .string()
    .optional()
    .describe(
      "A photo related to the product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type GetProductRecommendationsInput = z.infer<
  typeof GetProductRecommendationsInputSchema
>;

const GetProductRecommendationsOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe('An array of recommended product IDs. Should be between 3 to 5 products.'),
});
export type GetProductRecommendationsOutput = z.infer<
  typeof GetProductRecommendationsOutputSchema
>;

export async function getProductRecommendations(
  input: GetProductRecommendationsInput
): Promise<GetProductRecommendationsOutput> {
  return getProductRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getProductRecommendationsPrompt',
  input: {schema: GetProductRecommendationsInputSchema},
  output: {schema: GetProductRecommendationsOutputSchema},
  prompt: `You are an expert shopping assistant. Your goal is to recommend the best products from a provided list based on the user's profile.

  User Profile:
  - Summary: {{{userProfile.summary}}}
  - Tags: {{#each userProfile.tags}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

  Available Products (JSON format):
  {{{json products}}}
  
  {{#if photoDataUri}}
  The user also provided this photo for context: {{media url=photoDataUri}}
  {{/if}}

  Based on all the information, analyze the product list and select the 3 to 5 products that best match the user's profile and query. Return only the IDs of the recommended products.
  `,
});

const getProductRecommendationsFlow = ai.defineFlow(
  {
    name: 'getProductRecommendationsFlow',
    inputSchema: GetProductRecommendationsInputSchema,
    outputSchema: GetProductRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
